id: P004286
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4600
  title: རྒྱལ་དབང་འབྲུག་པ་དཀར་བརྒྱུད་ཕྲིན་ལས་ཤིང་རྟའི་རྣམ་ཐར།
  author: ''
  volumes:
    5072a49df56344eda479b0d596244b00:
      image_group_id: I1KG4610
      title: ''
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
