id: I5975449B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:50:13+00:00'
last_modified: '2022-06-07T21:41:50.078454+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4600
  title: རྒྱལ་དབང་འབྲུག་པ་དཀར་བརྒྱུད་ཕྲིན་ལས་ཤིང་རྟའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5445':
      image_group_id: I1KG4610
      title: ''
      total_pages: 326
      order: 1
      base_file: 5445.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
